# Generated by Django 4.2.5 on 2023-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='l_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
