# Generated by Django 4.2.5 on 2023-11-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_skills_alter_education_u_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='tools',
            new_name='image',
        ),
    ]
