# Generated by Django 4.2.5 on 2023-11-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_tools_skills_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
