# Generated by Django 4.2.5 on 2023-11-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_main_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='url',
            new_name='f_url',
        ),
        migrations.AddField(
            model_name='main',
            name='g_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='l_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='t_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
