# Generated by Django 4.2.5 on 2023-11-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usersign',
        ),
    ]
