# Generated by Django 4.2.5 on 2023-11-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_rename_user_usersign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersign',
        ),
    ]
