# Generated by Django 4.2.5 on 2023-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_data_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
