# Generated by Django 4.2.5 on 2023-10-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_data_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='name',
        ),
    ]
