# Generated by Django 4.2.5 on 2023-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_user_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
