# Generated by Django 4.2.5 on 2023-10-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_data1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data1',
        ),
    ]
